export const CONVERSATION_TYPES = {
  SET_CONVERSATION_LOADING: "SET_CONVERSATION_LOADING",
  SET_CONVERSATION_SUCCESS: "SET_CONVERSATION_SUCCESS",
  SET_CONVERSATION_ERROR: "SET_CONVERSATION_ERROR",
  SET_CONVERSATION_LAST_MESSAGE: "SET_CONVERSATION_LAST_MESSAGE",
  INCREMENT_NOTIFICATION: "INCREMENT_NOTIFICATION",
  EMPTY_NOTIFICATION: "EMPTY_NOTIFICATION",
};
